package Practice;

import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Created by Arthur 02.02.2018 17:24.
 */
public class App extends JDialog {
    private JButton inputButton;
    private JButton shButton;
    private JButton hafButton;

    private JToolBar toolBar;
    private JPanel root;
    private JPanel magicLayout;
    private JTextField textField1;

    public App() {
        shButton.setVisible(false);
        hafButton.setVisible(false);
        inputButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
//                JOptionPane.showMessageDialog(null, "ffff");
                shButton.setVisible(true);
                hafButton.setVisible(true);
            }
        });
    }

    public static void centerFrame(Window frame) {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (int) ((screenSize.getWidth() - frame.getWidth()) / 2);
        if (x < 0) {
            x = 0;
        }
        int y = (int) ((screenSize.getHeight() - frame.getHeight()) / 2);
        if (y < 0) {
            y = 0;
        }
        frame.setBounds(x, y, frame.getWidth(), frame.getHeight());
    }

    private void doit(JDialog jDialog) {

    }

    public static void main(String[] args) {
        JDialog jDialog = new JDialog();
        jDialog.setResizable(false);
        Window window = jDialog;
        jDialog.setContentPane(new App().root);
        jDialog.setVisible(true);
        jDialog.pack();
        centerFrame(window);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        root = new JPanel();
        root.setLayout(new FormLayout("fill:d:grow", "center:d:noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FormLayout("fill:193px:grow,fill:284px:noGrow,fill:max(d;4px):noGrow", "center:d:grow"));
        CellConstraints cc = new CellConstraints();
        root.add(panel1, cc.xy(1, 1));
        inputButton = new JButton();
        inputButton.setText("Входные данные");
        panel1.add(inputButton, cc.xy(1, 1));
        hafButton = new JButton();
        hafButton.setText("Кодирование Хаффмена");
        panel1.add(hafButton, cc.xy(3, 1));
        shButton = new JButton();
        shButton.setText("Кодирование Шеннона-Фано");
        panel1.add(shButton, cc.xy(2, 1));
        magicLayout = new JPanel();
        magicLayout.setLayout(new FormLayout("fill:d:grow,left:4dlu:noGrow,fill:max(d;4px):noGrow,left:4dlu:noGrow,fill:d:grow", "center:d:grow,top:4dlu:noGrow,center:max(d;4px):noGrow"));
        root.add(magicLayout, cc.xy(1, 3));
        textField1 = new JTextField();
        root.add(textField1, cc.xy(1, 5, CellConstraints.FILL, CellConstraints.DEFAULT));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return root;
    }
}